### PR TITLE
fix set_git_base_path and add paste_repos (from datastore)

### PR DESCRIPTION
**Pull request by yonicd**

### CODE REVIEW

**Comment by yonicd** [comment]
on the windows OS the .Renviron file writes out `\\` as `\`, then when its read back into R on the new session the `\` is not escaped and disappears.

**Comment by hafen** [comment]
Sorry -- I'm catching up on old email notifications! This looks good except for one thing that may sound nitpicky. We're enforcing a strict coding style for all HBGDki projects, based on what is found [here](http://r-pkgs.had.co.nz/r.html#style). For example, all lowercase camel case, spacing around operators, using `<-` consistently, newlines with pipes for readability, etc. Could you modify to meet these guidelines?

**Comment by yonicd** [comment]
code is tidy now

**Comment by hafen** [comment]
Thanks! Feel free to add yourself as a contributor in DESCRIPTION.

**Pull request merged**
